global:
  resolve_timeout: 5m
receivers:
- name: prometheus-msteams
  webhook_configs:
  - url: "http://prometheus-msteams:2000/alert"
    send_resolved: true
route:
  group_by:
  - job
  group_interval: 30s
  group_wait: 30s
  receiver: prometheus-msteams
  repeat_interval: 12h
  routes:
  - match:
      alertname: Watchdog
    receiver: prometheus-msteams